services:
  catalogue:
    build:
      context: .
      args:
        - COMMIT_SHA='commit_sha'
        - RELEASE_TAG='dev'
    image: azumax/catalogue-4:test
    container_name: "catalogue-4"
    environment:
      - NEW_RELIC_APP_NAME=local_catalogue-4
      - NEW_RELIC_LICENSE_KEY=
      - NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true
      - NEW_RELIC_INFINITE_TRACING_TRACE_OBSERVER_HOST=
      - DB_HOST=catalogue-db-4
      - RAILS_LOG_TO_STDOUT=true
    ports:
      - "3000:3000"
  catalogue-db-4:
    image: azumax/catalogue-db-4:test
    container_name: "catalogue-db-4"
    environment:
      - MYSQL_ROOT_PASSWORD=fake_password
      - MYSQL_DATABASE=socksdb
    ports:
      - "3306:3306"
